// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Portal.Data;

namespace Portal.Migrations
{
    [DbContext(typeof(PortalContext))]
    [Migration("20201130063804_Admin")]
    partial class Admin
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Portal.Models.Admin", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Fa1")
                        .HasColumnType("int");

                    b.Property<int>("Fa2")
                        .HasColumnType("int");

                    b.Property<int>("Fa3")
                        .HasColumnType("int");

                    b.Property<float>("FaAve")
                        .HasColumnType("real");

                    b.Property<float>("Finals")
                        .HasColumnType("real");

                    b.Property<string>("First_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Fq1")
                        .HasColumnType("int");

                    b.Property<int>("Fq2")
                        .HasColumnType("int");

                    b.Property<int>("Fq3")
                        .HasColumnType("int");

                    b.Property<float>("FqAve")
                        .HasColumnType("real");

                    b.Property<string>("Last_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ma1")
                        .HasColumnType("int");

                    b.Property<int>("Ma2")
                        .HasColumnType("int");

                    b.Property<int>("Ma3")
                        .HasColumnType("int");

                    b.Property<float>("MaAve")
                        .HasColumnType("real");

                    b.Property<float>("Midterm")
                        .HasColumnType("real");

                    b.Property<int>("Mq1")
                        .HasColumnType("int");

                    b.Property<int>("Mq2")
                        .HasColumnType("int");

                    b.Property<int>("Mq3")
                        .HasColumnType("int");

                    b.Property<float>("MqAve")
                        .HasColumnType("real");

                    b.Property<int>("Pa1")
                        .HasColumnType("int");

                    b.Property<int>("Pa2")
                        .HasColumnType("int");

                    b.Property<int>("Pa3")
                        .HasColumnType("int");

                    b.Property<float>("PaAve")
                        .HasColumnType("real");

                    b.Property<int>("Pfa1")
                        .HasColumnType("int");

                    b.Property<int>("Pfa2")
                        .HasColumnType("int");

                    b.Property<int>("Pfa3")
                        .HasColumnType("int");

                    b.Property<float>("PfaAve")
                        .HasColumnType("real");

                    b.Property<int>("Pfq1")
                        .HasColumnType("int");

                    b.Property<int>("Pfq2")
                        .HasColumnType("int");

                    b.Property<int>("Pfq3")
                        .HasColumnType("int");

                    b.Property<float>("PfqAve")
                        .HasColumnType("real");

                    b.Property<int>("Pq1")
                        .HasColumnType("int");

                    b.Property<int>("Pq2")
                        .HasColumnType("int");

                    b.Property<int>("Pq3")
                        .HasColumnType("int");

                    b.Property<float>("PqAve")
                        .HasColumnType("real");

                    b.Property<float>("Prefinals")
                        .HasColumnType("real");

                    b.Property<float>("Prelim")
                        .HasColumnType("real");

                    b.Property<string>("StudentID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Admin");
                });
#pragma warning restore 612, 618
        }
    }
}
